FROM openjdk:17.0.2-jdk
ARG VERSION=0.5
ARG PAPI_AUTH_PASSWORD
ARG PAPI_COMPUTER_CONTROL_AUTH_PASSWORD
ARG PAPI_GITHUB_AUTH
COPY ./build/libs/project-apis-${VERSION}.jar poject-apis.jar
ENV PAPI_AUTH_PASSWORD=${PAPI_AUTH_PASSWORD}
ENV PAPI_COMPUTER_CONTROL_AUTH_PASSWORD=${PAPI_COMPUTER_CONTROL_AUTH_PASSWORD}
ENV PAPI_GITHUB_AUTH=${PAPI_GITHUB_AUTH}
EXPOSE 8080
ENTRYPOINT ["java","-jar","/project-apis.jar"]